CREATE TABLE `item` (
  `ID_ITEM` int(11) NOT NULL AUTO_INCREMENT,
  `nameItem` varchar(45) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Field to save the name of the items that customer can create // Campo para guardar el nombre de los artículos que el cliente puede crear',
  `itemCategoryType` int(11) NOT NULL COMMENT 'Field to save the id of category, because we can have a lot of categorys // Campo para guardar el id de categoría, porque podemos tener muchas categorías',
  `itemSubcategoryType` int(11) NOT NULL COMMENT 'Field to save the id of subcategory, because we can have a lot of subcategorys // Campo para guardar el id de la subcategoría, porque podemos tener muchas subcategorías',
  `customerSeller` int(11) NOT NULL COMMENT 'Field to save the id of the customer seller // Campo para guardar el id del cliente vendedor',
  `descriptionItem` text COLLATE utf8_spanish_ci NOT NULL COMMENT 'Field to save the description of the item offered // Campo para guardar la descripción del artículo ofertado',
  `slugItem` varchar(45) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Field to save then name of the slug, this field like others slug  can be used to support the developer team // Campo para guardar el nombre del slug, este campo, al igual que otros slug, se puede usar para ayudar al equipo de desarrolladores',
  `price` float(18,2) NOT NULL COMMENT 'Field to save the price of the item // Campo para guardar el precio del artículo',
  `statusItem` tinyint(4) NOT NULL DEFAULT 1 COMMENT 'Field to save the status of the item we can save 1 for Active or 0 for inactive // Campo para guardar el estado del artículo podemos guardar 1 para Activo o 0 para inactivo',
  `datePublished` datetime NOT NULL DEFAULT current_timestamp() COMMENT 'This field save the date of the published the item this field we can be use to partitioning the table , but remember Mysql doesn''t support partition with index field only you can use partition or index but not both at the same time // Este campo guarda la fecha de publicación del elemento. Este campo se puede usar para particionar la tabla, pero recuerde que Mysql no admite particiones con campo de índice. Solo puede usar partición o índice, pero no ambos al mismo tiempo.',
  `dateDropItem` datetime DEFAULT NULL COMMENT 'Field to save the drop item remember the logic erased // Campo para guardar el elemento drop recordar la lógica borrada',
  `dateLastUpdate` datetime DEFAULT NULL COMMENT 'Field to save the last update in the row // Campo para guardar la última actualización en la fila',
  `stock` int(11) NOT NULL COMMENT 'Field to save the stock of the items // Campo para guardar el stock de los artículos',
  `isActive` tinyint(4) NOT NULL DEFAULT 1 COMMENT 'Field to save the status account  // Campo para guardar el estado de la cuenta --  borrado logico. ',
  `sourceName` varchar(4) COLLATE utf8_spanish_ci DEFAULT 'item' COMMENT 'Field to save automatically the name of the source because when you use this table in some join you case see the table in the result of the script // Campo para guardar automaticamente el nombre de la tabla ya que cuando esta tabla pueda ser usada en algun join en la consulta resultante pueda ver la tabla -- esto en caso de que el GUI no diferencie las tablas por colores.',
  PRIMARY KEY (`ID_ITEM`,`datePublished`),
  KEY `fk_itemCategoryType` (`itemCategoryType`),
  KEY `fk_itemSubcategoryType` (`itemSubcategoryType`),
  KEY `fk_customerSeller` (`customerSeller`),
  CONSTRAINT `fk_customerSeller` FOREIGN KEY (`customerSeller`) REFERENCES `customer` (`ID_CUSTOMER`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_itemCategoryType` FOREIGN KEY (`itemCategoryType`) REFERENCES `category` (`ID_CATEGORY`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_itemSubcategoryType` FOREIGN KEY (`itemSubcategoryType`) REFERENCES `subcategory` (`ID_SUBCATEGORY`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=357 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='This table contains the data of  items like in the Meli exercise Items';
