CREATE TABLE `order` (
  `ID_ORDER` int(11) NOT NULL AUTO_INCREMENT,
  `orderNumber` varchar(45) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Field to save the order number, this field can be created in Backend code or SP // Campo para guardar el número de pedido, este campo se puede crear en el código Backend o SP',
  `idCustomer` int(11) NOT NULL COMMENT 'Field to save the id of the customer this customer can be seller or buyer, key field // Campo para guardar el id del cliente este cliente puede ser vendedor o comprador, campo clave',
  `idItemOrder` int(11) NOT NULL COMMENT 'Field to save the id of item because the order can contains a lot of items , key field // Campo para guardar la identificación del artículo porque el pedido puede contener muchos artículos campo cable',
  `payment` float(18,2) DEFAULT NULL COMMENT 'Field to save the payment that user can do //  Campo para guardar el pago que puede hacer el usuario',
  `quantity` int(11) DEFAULT NULL COMMENT 'Field to save the quantity of items the user can order // Campo para guardar la cantidad de artículos que el usuario puede pedir',
  `tax` float(18,2) DEFAULT NULL COMMENT 'Field to save the tax value that the user can be pay // Campo para guardar el valor del impuesto que el usuario puede pagar',
  `email` varchar(45) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Field to save the same email of the user or other email to contact  // Campo para guardar el mismo email del usuario u otro email para contactar',
  `phone` varchar(45) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Field to save the same phone of the user or other phone to contact // Campo para guardar el mismo teléfono del usuario u otro teléfono para contactar',
  `address` varchar(45) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Field to save the same address of the user or other address to contact // Campo para guardar la misma dirección del usuario u otra dirección a contactar',
  `city` varchar(45) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Field to save the city for delivery package// Campo para guardar la ciudad para el paquete de entrega',
  `state` varchar(45) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Field to save the state for delivery package // Campo para guardar el departamento para el paquete de entrega',
  `country` varchar(45) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Field to save the state for delivery package // Campo para guardar el departamento para el paquete de entrega',
  `statusOrder` enum('New','Accepted','Completed','Canceled') COLLATE utf8_spanish_ci NOT NULL COMMENT 'Field to save the status of the order, the order can be save New, Accepted, Completed, Canceler, I use the ENUM because I''m trying to use other thing, but easily can use one join o fk // Campo para guardar el estado del pedido, el pedido se puede guardar Nuevo, Aceptado, Completado, Cancelador, uso ENUM porque estoy tratando de usar otra cosa, pero puedo usar fácilmente una unión o fk',
  `ip` varchar(45) COLLATE utf8_spanish_ci NOT NULL COMMENT 'Field to save the public ip of the user in the time // Campo para guardar la ip publica del usuario',
  `dateCreateAt` datetime NOT NULL DEFAULT current_timestamp() COMMENT 'Field to save the date of created // Campo para guardar la fecha de creación',
  `dateLastUpdate` datetime NOT NULL COMMENT 'Field to save the last update of the row // Campo para guardar la última actualización de la fila',
  `sourceName` varchar(6) COLLATE utf8_spanish_ci NOT NULL DEFAULT 'order' COMMENT 'Field to save automatically the name of the source because when you use this table in some join you case see the table in the result of the script // Campo para guardar automaticamente el nombre de la tabla ya que cuando esta tabla pueda ser usada en algun join en la consulta resultante pueda ver la tabla -- esto en caso de que el GUI no diferencie las tablas por colores.',
  `isActive` tinyint(4) NOT NULL DEFAULT 1 COMMENT 'Field to save the status account  // Campo para guardar el estado de la cuenta --  borrado logico. ',
  PRIMARY KEY (`ID_ORDER`),
  KEY `fk_idCustomer` (`idCustomer`),
  KEY `fk_idItemOrder` (`idItemOrder`),
  CONSTRAINT `fk_idCustomer` FOREIGN KEY (`idCustomer`) REFERENCES `customer` (`ID_CUSTOMER`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_idItemOrder` FOREIGN KEY (`idItemOrder`) REFERENCES `item` (`ID_ITEM`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=347 DEFAULT CHARSET=utf8 COLLATE=utf8_spanish_ci COMMENT='This table contains the data of Order like in the Meli exercise Order';
